language: node_js
node_js:
  - node

cache:
  directories:
    - 'node_modules'

branches:
  only:
  - master

install:
  - npm install
  - npm run build
  - npm run export

script:
  - echo "Skipping tests"

after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis" # this email and name can be set anything you like
  - git add docs/
  - git commit --allow-empty -m "Deploy"
  - git push https://dubchenko:${GITHUB_API_KEY}@${GH_REF} HEAD:master