dist: xenial
language: node_js
node_js:
  - node

cache:
  directories:
    - 'node_modules'

branches:
  only:
  - develop

install:
  - npm install
  - npm run build
  - npm run export 

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  cleanup: false
  keep_history: true
  token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local-dir: dist
  on:
    branch: develop