language: node_js
node_js:
  - node

cache:
  directories:
    - 'node_modules'

branches:
  only:
  - master

install:
  - npm install
  - npm run build
  - npm run export

script:
  - echo "Skipping tests"